package com.pcitc.fms.service.stormModel;

/**
 * Generated by MyGeneration using the IBatis Object Mapping template
 * @author lzp
 *
 */
public class AirDen {
	private Boolean isChanged;
	private Boolean isDeleted;
    private Double FLOG_MOD_COEF;//浮力修正系数
    private Double FLOG_MOD_VAL;//浮力修正值
    
	public Double getFLOG_MOD_COEF() {
		return FLOG_MOD_COEF;
	}
	public void setFLOG_MOD_COEF(Double fLOG_MOD_COEF) {
		FLOG_MOD_COEF = fLOG_MOD_COEF;
	}
	public Double getFLOG_MOD_VAL() {
		return FLOG_MOD_VAL;
	}
	public void setFLOG_MOD_VAL(Double fLOG_MOD_VAL) {
		FLOG_MOD_VAL = fLOG_MOD_VAL;
	}
    
	 public AirDen(){
			
		}
	public Boolean getIsChanged() {
		return isChanged;
	}
	public Boolean getIsDeleted() {
		return isDeleted;
	}
	public void MarkAsDeleted()
	{
		isDeleted = true;
		isChanged = true;
	}
}

